#  線形代数

## スカラー、ベクトル、行列

### スカラーとは？

スカラー（scalar）は1、5、1.2、-7などの通常の数値のことである。

数式におけるアルファベット、もしくはギリシャ文字の小文字はスカラーを表すものとする。（例: $a$、$p$、$\alpha$、$\gamma$）  

### ベクトルとは？

ベクトルは、スカラーを直線上に並べたものです。

アルファベットの小文字に矢印を乗せたものでベクトルを表します。以下はベクトルの表記の例です。

$$ \begin{aligned}
\vec{a} & = \left(
    \begin{array}{c}
      1 \\
      2 \\
      3
    \end{array}
 \right) \\
 \vec{p} & = \left(
    \begin{array}{c}
      p_1 \\
      p_2 \\
      \vdots \\
      p_m
    \end{array}
 \right) \\
\end{aligned} $$


また、転置を行うと、下記のように縦横を入れ替える。
$$ \begin{aligned}
\vec{a}^T & = \left(
    \begin{array}{ccc}
      1 & 2 & 3
    \end{array}
 \right) \\
 \end{aligned} $$

### 行列とは？

行列はスカラーを格子状に並べたものである。

アルファベット大文字のイタリックで行列を表します。以下は行列の表記の例です。  

$$
   A = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
    \end{array}
  \right)
$$
$$
   P = \left(
    \begin{array}{cccc}
      p_{11} & p_{12} & \ldots & p_{1n} \\
      p_{21} & p_{22} & \ldots & p_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      p_{m1} & p_{m2} & \ldots & p_{mn} \\
    \end{array}
  \right) 
$$

行列$A$は2x3の行列で、行列$P$はm x nの行列です。  
また、$P$に見られるように、行列の要素を変数で表す際の添字の数は2つです。


### スカラー、ベクトル、行列の実装

In [81]:
import numpy as np

# スカラー
a = 1  
print('スカラー：',a)
print()

# ベクトル
a = np.array([1, 2, 3]) 
print('ベクトル：',a)
print()

# 2x3の行列
a = np.array([[1, 2, 3],
              [4, 5, 6]])  
print('行列：',a)

スカラー： 1

ベクトル： [1 2 3]

行列： [[1 2 3]
 [4 5 6]]


## 変数の表記について

小文字で細字：スカラーの変数 \
大文字で細字：スカラーの定数 \
小文字で太字：ベクトルの変数 \
大文字で太字：行列

## 行列の演算

### ベクトルの足し算

$$ \begin{aligned}
\left(
    \begin{array}{c}
      1 \\
      2 \\
      3
    \end{array}
\right)  +  \left(
    \begin{array}{c}
      4 \\
      5 \\
      6
    \end{array}
 \right) =  \left(
    \begin{array}{cc}
      1 & + & 4 \\
      2 & + & 5 \\
      3 & + & 6
    \end{array}
 \right) =  \left(
    \begin{array}{c}
      5 \\
      7 \\
      9
    \end{array}
 \right) 
\end{aligned} $$

### ベクトルの引き算

$$ \begin{aligned}
\left(
    \begin{array}{c}
      1 \\
      2 \\
      3
    \end{array}
\right)  -  \left(
    \begin{array}{c}
      6 \\
      5 \\
      4
    \end{array}
 \right) =  \left(
    \begin{array}{cc}
      1 & - & 6 \\
      2 & - & 5 \\
      3 & - & 4
    \end{array}
 \right) =  \left(
    \begin{array}{c}
      -5 \\
      -3 \\
      -1
    \end{array}
 \right) 
\end{aligned} $$

### 行列の足し算

$$ \begin{aligned}
\left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 
    \end{array}
\right)  +  \left(
    \begin{array}{ccc}
      7 & 8 & 9 \\
      10 & 11 & 12 
    \end{array}
 \right) =  \left(
    \begin{array}{ccc}
      1+7  & 2+8  & 3+9 \\
      4+10 & 5+11 & 6+12
    \end{array}
 \right) =  \left(
    \begin{array}{ccc}
      8  & 10 & 12 \\
      14 & 16 & 18
    \end{array}
 \right) 
\end{aligned} $$

#### ポイント

サイズが同じであることが計算できる条件

### 行列の演算の実装

In [82]:
# ベクトルの足し算
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
print('元の値：',a)
print('元の値：',b)
print('ベクトルの足し算',a + b)
print('----------')

# ベクトルの引き算
a = np.array([1, 2, 3]) 
b = np.array([6, 5, 4]) 
print('元の値：',a)
print('元の値：',b)
print('ベクトルの引き算',a - b)
print('----------')

# ベクトルの掛け算
print('元の値：',a)
print('元の値：',b)
print('ベクトルの掛け算',a * b)
print('----------')

# 行列の足し算
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [10,11,12]])  
print('元の値：',A)
print('元の値：',B)
print('行列の足し算',A + B)

元の値： [1 2 3]
元の値： [4 5 6]
ベクトルの足し算 [5 7 9]
----------
元の値： [1 2 3]
元の値： [6 5 4]
ベクトルの引き算 [-5 -3 -1]
----------
元の値： [1 2 3]
元の値： [6 5 4]
ベクトルの掛け算 [ 6 10 12]
----------
元の値： [[1 2 3]
 [4 5 6]]
元の値： [[ 7  8  9]
 [10 11 12]]
行列の足し算 [[ 8 10 12]
 [14 16 18]]


### 行列積

$$ \begin{aligned}
\left(
    \begin{array}{cc}
      1 & 2  \\
      3 & 4  
    \end{array}
\right)   \left(
    \begin{array}{cc}
      5 & 6 \\
      7 & 8 
    \end{array}
 \right) =  \left(
    \begin{array}{cc}
      1\times 5+2\times 7 & 1\times 6+2\times 8 \\
      3\times 5+4\times 7 & 3\times 6+4\times 8
    \end{array}
 \right) =  \left(
    \begin{array}{cc}
      19 & 22 \\
      43 & 50
    \end{array}
 \right) 
\end{aligned} $$

※行列積の場合は、「×」を記述しない。 \
$\left(
    \begin{array}{cc}
      1 & 2  \\
      3 & 4  
    \end{array}
\right) \times  \left(
    \begin{array}{cc}
      5 & 6 \\
      7 & 8 
    \end{array}
 \right)$と記載すると、足し算や引き算と同じやり方で各項目の掛け算を行う。

#### ポイント

行列Ａと行列Ｂの行列積を求めるためには、Ａの列数とＢの行数が一致することが条件である。 \
また、計算結果はＡの行数×Ｂの列数の行列が作成される。

## 重回帰分析でよく使う計算

（１）１行ｎ列のベクトルと、ｎ行１列のベクトルとの行列積は、必ず**スカラー**となる。

$$ \begin{aligned}
\left(
    \begin{array}{cc}
      1 & 2  
    \end{array}
\right)   \left(
    \begin{array}{c}
      3  \\
      4  
    \end{array}
 \right) =  \left(
    \begin{array}{c}
      1\times 3+2\times 4 
    \end{array}
 \right) =  11
\end{aligned} $$


公式（１）　**$ \vec{a}^T \vec{b}$ はスカラー**

（２）行列とベクトルの行列積は、必ず**ベクトル**となる。

$$ \begin{aligned}
\left(
    \begin{array}{cc}
      1 & 2  \\
      3 & 4  
    \end{array}
\right)   \left(
    \begin{array}{c}
      5 \\
      6 
    \end{array}
 \right) =  \left(
    \begin{array}{c}
      1\times 5+2\times 6 \\
      3\times 5+4\times 6 
    \end{array}
 \right) =  \left(
    \begin{array}{c}
      17  \\
      39 
    \end{array}
 \right) 
\end{aligned} $$

公式（２）　**$X \vec{b}$ はベクトル**

（３）１行ｎ列のベクトルと、ｎ行ｎ列の行列と、ｎ行１列のベクトルとの行列積は、必ず**スカラー**となる。

$$ \begin{aligned}
\left(
    \begin{array}{cc}
      1 &  2
    \end{array}
\right)   \left(
    \begin{array}{cc}
      3 & 4 \\
      5 & 6
    \end{array}
 \right)  \left(
    \begin{array}{c}
      3  \\
      1 
    \end{array}
 \right)  &=  \left(
    \begin{array}{cc}
      1 & 2
    \end{array}
\right) \left(
    \begin{array}{c}
      3\times 3+4\times 1 \\
      5\times 3+6\times 1 
    \end{array}
 \right) \\
  &=  \left(
    \begin{array}{cc}
      1 & 2
    \end{array}
\right) \left(
    \begin{array}{c}
      13 \\
      21 
    \end{array}
 \right) \\
 &=  \left(
    \begin{array}{c}
      1\times 13+2\times 21
    \end{array}
 \right) \\
 &= 55
\end{aligned} $$

公式（３） **$ \vec{a}^T B \vec{c}$ はスカラー**

### 行列積の実装

In [83]:
a = np.array([1, 2])
b = np.array([[3], [4]])  
print('元の値：',a)
print('元の値：',b)
print('行列積',np.dot(a ,b))
print('----------')

A = np.array([[1, 2],
              [3, 4]])
b = np.array([[5], [6]])  
print('元の値：',A)
print('元の値：',b)
print('行列積',np.dot(A, b))
print('----------')

a = np.array([1, 2])
B = np.array([[3, 4],
              [5, 6]])
c = np.array([[3], [1]])  
print('元の値：',a)
print('元の値：',B)
print('元の値：',c)
print('行列積', np.dot(a ,np.dot(B, c)))
print('行列積', np.dot(np.dot(a ,B) ,c))

元の値： [1 2]
元の値： [[3]
 [4]]
行列積 [11]
----------
元の値： [[1 2]
 [3 4]]
元の値： [[5]
 [6]]
行列積 [[17]
 [39]]
----------
元の値： [1 2]
元の値： [[3 4]
 [5 6]]
元の値： [[3]
 [1]]
行列積 [55]
行列積 [55]


## 転置

ベクトルの場合は、縦横が入れ替わる。

$$ \begin{aligned}
\vec{a} &= \left(
    \begin{array}{c}
      1 \\
      2 \\
      3
    \end{array}
 \right) \\
 \vec{a}^T &= \left(
    \begin{array}{ccc}
      1 & 2 & 3
    \end{array}
 \right) \\
 \end{aligned} $$

行列の場合は、

$$ \begin{aligned}
X&=\left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 
    \end{array}
\right) \\
X^T&=\left(
    \begin{array}{cc}
      1 & 4 \\
      2 & 5 \\
      3 & 6 
    \end{array}
\right) 
 \end{aligned} $$

###  転置の公式

（４） $ \left(A^T\right)^T=A $ \
\
（５） $ \left(AB\right)^T=B^TA^T $ \
\
（６） $ \left(ABC\right)^T=C^TB^TA^T $ 

転置の実装

In [84]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print('宣言時',A)
print('転置後',A.T)
print('-----------------')

B=A.T
print('転置後にもう一度転置',B.T)
print('-----------------')

B = np.array([[7, 8],
              [9, 10],
              [11,12]])
C = np.dot(A ,B)
print('行列積の転置',C.T)
print('転置後の行列積',np.dot(B.T ,A.T))
print('-----------------')

宣言時 [[1 2 3]
 [4 5 6]]
転置後 [[1 4]
 [2 5]
 [3 6]]
-----------------
転置後にもう一度転置 [[1 2 3]
 [4 5 6]]
-----------------
行列積の転置 [[ 58 139]
 [ 64 154]]
転置後の行列積 [[ 58 139]
 [ 64 154]]
-----------------


## 単位行列

スカラーの１に相当する行列である。

$$ \begin{aligned}
I&=\left(
    \begin{array}{cccc}
      1 & 0 & \ldots & 0 \\
      0 & 1 & \ldots & 0 \\
      \vdots & \vdots & \ddots & \vdots \\
      0 & 0 & \ldots & 1 \\
    \end{array}
\right) \\
\end{aligned} $$

### 単位行列の公式

（７） $ AI=A $ \
\
（８） $ IA=A $ 

## 単位行列の実装

In [85]:
# ３行３列の単位行列
I=np.eye(3)
print('単位行列',I)
print('-----------------')

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print('元の値：',A)
print('行列×単位行列：',np.dot(A , I))
print('単位行列×行列：',np.dot(I , A))

単位行列 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------
元の値： [[1 2 3]
 [4 5 6]
 [7 8 9]]
行列×単位行列： [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
単位行列×行列： [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 逆行列

スカラーの逆数にあたる内容である。例として、２の逆数は $\frac{1}{2}$である。（答えが１になる値）

行列の場合は、単位行列となる値である。（下記の$A^{-1}$は「エーインバース」と読む）

$$ \begin{aligned}
 AA^{-1}=I \\
 A^{-1}A=I
\end{aligned} $$


逆行列が求まる条件 \
①正方行列であること。 （正方行列でない場合は、エラーになる）


## ベクトルの微分

例（１）

$$ \begin{aligned}
\vec{c} &= \left(
    \begin{array}{c}
      3 \\
      4
    \end{array}
 \right) \\
 \vec{x} &= \left(
    \begin{array}{c}
      x_1 \\
      x_2
    \end{array}
 \right) \\
  \end{aligned} $$
 
の時に $\vec{c}^T\vec{x}$ に対して、$\vec{x}$ で微分する。

$$ \begin{aligned}
  \vec{c}^T\vec{x} &= \left(
    \begin{array}{cc}
      3 & 4
    \end{array}
  \right) 
  \left(
    \begin{array}{c}
      x_1 \\
      x_2
    \end{array}
  \right) \\
  &= 3  x_1 + 4  x_2 \\
  \\
  \\
  \frac{\partial}{\partial \vec{x}}(\vec{c}^T\vec{x})
  &=\left(
    \begin{array}{c}
      \frac{\partial}{\partial x_1}(3  x_1 + 4  x_2) \\
      \frac{\partial}{\partial x_2}(3  x_1 + 4  x_2)
    \end{array}
  \right) \\
  \\
  \\
  \frac{\partial}{\partial x_1}(3  x_1 + 4  x_2)
  &= \frac{\partial}{\partial x_1}(3x_1) + \frac{\partial}{\partial x_1}(4x_2) \\
  &= 3 \\
  \\
  \\
  \frac{\partial}{\partial x_2}(3  x_1 + 4  x_2)
  &= \frac{\partial}{\partial x_2}(3x_1) + \frac{\partial}{\partial x_2}(4x_2) \\
  &= 4 \\
  \\
  \\
  \frac{\partial}{\partial \vec{x}}(\vec{c}^T\vec{x}) 
  &=\left(
    \begin{array}{c}
      3 \\
      4
    \end{array}
  \right) \\
\end{aligned} $$

### 公式  (The Matrix Cookbook 　公式が載ったPDF　2.4章)

（９） $ \frac{\partial}{\partial \vec{x}}(\vec{c}) = \vec{0} $ \
\
（１０） $ \frac{\partial}{\partial \vec{x}}(\vec{c}^T\vec{x})= \vec{c} $ \
\
（１１） $  \frac{\partial}{\partial \vec{x}}(\vec{x}^TA\vec{x})= (A + A^T)\vec{x} $ 