## 行列演算の基礎

$$ w=(X^TX)^{-1}X^Ty$$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [3]:
#ベクトルの定義
x=np.array([[1],[2],[3]])

In [13]:
#行列の定義
X=np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [14]:
#転置
xt=X.T

In [15]:
# 逆行列
# linear algebra : 線形代数
X_inv=np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# 行列積
XX_inv=np.dot(X ,X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## 演習問題

In [20]:
X=np.array([[1,2,3],[1,2,5],[1,3,4],[1,5,9]])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [21]:
y=np.array([[1],[5],[6],[8]])
print(y)

[[1]
 [5]
 [6]
 [8]]


# 求める手順
- Step1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- Step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$  Step1の逆行列
- Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- Step4：w=$(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [24]:
# Step1
XtX=np.dot(X.T ,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [26]:
# Step2
XtX_inv=np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [31]:
# Step3
Xty=np.dot(X.T ,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [34]:
# Step4
w=np.dot(XtX_inv ,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


In [36]:
# 重回帰分析のライブラリ読み込み
import sklearn
from sklearn.linear_model import LinearRegression

In [37]:
# モデルの宣言　（modelという変数を初期化する）
model = LinearRegression()

In [40]:
# モデルの学習　←パラメータを調整する (Step 1～4までを自動的に処理する)
model.fit(X , y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [43]:
# 調整後のパラメータ　（Step4 の w を求めてくれる）
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [47]:
# 予測精度　←決定係数　０は論外　１は完璧
model.score(X ,y)

0.6923076923076926

In [50]:
# 予測値の計算
x = np.array([[1,2,3]])
y_pred=model.predict(x)
print(y_pred)

[[3.]]
